//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stud.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class studentEntities : DbContext
    {
        public studentEntities()
            : base("name=studentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal void SaveChanges()
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Login_Password_Stud> Login_Password_Stud { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public object Groups { get; internal set; }
    }
}
