//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stud.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int ID_Stud { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronomic { get; set; }
        public Nullable<int> ID_Log_Pass_Stud { get; set; }
        public System.DateTime Date_Birthday { get; set; }
        public int ID_Group { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Login_Password_Stud Login_Password_Stud { get; set; }
        public object ID_Login { get; internal set; }
        public string Patronumic { get; internal set; }
    }
}
